---
title: "assignment04_dk1096"
author: "Da Sul Kim"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(tibble)
library(WDI)
library(dplyr)
library(ggrepel)
library(sjPlot)
```

```{r setting dataset, include = FALSE}
informaldata<- read_xlsx("data/informaldata.xlsx")
WDI <- WDI(
  country = "all",
  indicator = c("DT.ODA.OATL.KD",
  "DT.ODA.ODAT.CD",
  "DT.ODA.ALLD.KD",
  "DC.DAC.TOTL.CD",
  "GC.DOD.TOTL.GD.ZS",
  "GC.XPN.TOTL.GD.ZS",
  "NE.EXP.GNFS.ZS",
  "BX.KLT.DINV.WD.GD.ZS",
  "NY.GDP.MKTP.KD",
  "NY.GDP.PCAP.KD",
  "NY.GDP.PCAP.KD.ZG",
  "NE.CON.GOVT.ZS",
  "SE.XPD.TOTL.GD.ZS",
  "MS.MIL.XPND.GD.ZS",
  "NY.GDP.PETR.RT.ZS",
  "BX.TRF.PWKR.DT.GD.ZS",
 "GC.TAX.TOTL.GD.ZS",
  "SE.PRM.TENR",
  "SP.URB.TOTL.IN.ZS",
  "SP.POP.TOTL",
  "SI.POV.DDAY",
  "SI.POV.LMIC",
  "SI.POV.UMIC"),
  start = 1960,
  end = 2020,
  extra = TRUE,
  cache = NULL,
  latest = NULL,
  language = "en")
colnames(WDI)[27] <- "scode"

polity <- read_xls("data/p5v2018.xls")

new <- left_join(x = WDI, y=polity, by=c("year", "scode"))
new <- left_join(x = new, y = informaldata, by = c("year", "scode"))
```

## Four ggplot2 graphs

# Graph 1. 
```{r graph1}
new %>% 
  drop_na(region, MIMIC_p) %>% 
  ggplot(aes(x = region, y = MIMIC_p, group=region, fill=region))+
  geom_boxplot() +
  theme(legend.position="none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_fill_brewer(palette="BuPu") +
  labs(x = "",
       y = "The Share of Informal Economy (% of GDP)",
       title = "The Share of Informal Economy by Region",
       subtitle = "Source: World Bank",
       caption = "The share of informal economy is calculated using multiple indicators multiple causes model-based (MIMIC) estimates of informal output (% of official GDP)"
  )

```


# Graph 2.
```{r graph2}
new %>% 
  mutate(oda_gdp = DT.ODA.ODAT.CD/NY.GDP.MKTP.KD*100) %>% 
  filter(country.x == "Ethiopia") %>%
  drop_na(oda_gdp) %>% 
  ggplot(aes(x = year, y = oda_gdp)) +
  geom_line() +
  scale_y_continuous(breaks=c(5, 10, 15))+
  theme_minimal()+
  labs(x = "Year",
       y = "The Share of net ODA (% of GDP)",
       title = "The Share of ODA in Ethiopia (% of GDP)",
       caption = "Source: World Bank")
```

# Graph 3.
```{r}
new %>% 
  filter(region == "Sub-Saharan Africa",
         year ==2010) %>% 
  mutate(pop = SP.POP.TOTL/1000000,
         oda_gdp = DT.ODA.ODAT.CD/NY.GDP.MKTP.KD*100) %>% 
  ggplot(aes(x = oda_gdp, y=DGE_p, col = income, size = pop)) +
  geom_point(alpha = 0.5) +
  scale_x_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60, 70)) +
  theme_classic()+
  theme(plot.title = element_text(hjust=0.5),
        panel.background=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.y=element_blank(),
        axis.ticks=element_blank(),
        panel.border=element_blank())+
  labs( x= "The Share of ODA (% of GDP)",
        y = "The Share of Informal Economy (DGE) (%of GDP)",
        size = "Population (in millions)",
        col = "Income Group",
        subtitle = "Source: World Bank",
        caption = "Dynamic general equilibrium model-based (DGE) estimates of informal output (% of official GDP)",
        title = "Informal Economy and ODA in Sub-Saharan Africa in 2010")
```

# Graph 4.
```{r}
 new %>% 
  filter(!(region=="Aggregates")) %>% 
  mutate(pop = SP.POP.TOTL/1000000) %>% 
  ggplot(aes(x=SE.PRM.TENR, y=Infsize_p)) +
  geom_jitter(aes(col=income, size=pop)) +
  geom_smooth(aes(col=income), method="lm", se=F)+
  theme_bw() +
  labs(x= "Primary School Enrollment Rate (% of primary school age children)",
       y = "The Share of Informal Economy (MIMIC) (%of GDP)",
       size = "Population (in millions)",
       col = "Income Group",
       subtitle = "Source: World Bank",
       caption = "The Share of Informal Economy: employment outside the formal sector (% of total employment; International Labour Organization; hamonized series)",
       title = "Informal Economy and Primary School Enrollment Rate from 1990 to 2000")
```



